# 站点名称
site_name: RoninssWang-Blog
# 仓库链接
repo_url: https://github.com/example/repository/
# 作者
site_author: 'sswang'
# 版权信息
copyright: '2021, sswang'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 主题
theme:
  # name: 'readthedocs'
  # name: 'mkdocs'
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  features:
    - navigation.instant
    - navigation.tabs # 栏头加标签（一级导航）
    # - navigation.tabs.sticky # 固定（浏览时不收起）标签
    # tabs: true
  language: 'zh'
# 额外信息
extra:
  # 版本号
  version: 0.1.0
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
plugin:
    - search:
      lang: 
        - en
      separator: '[\s\-\.]+'
# markdown扩展
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes # 支持脚注
  - meta
  - def_list
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex
   # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/baidu-tongji.js

# 导航
nav:
- Home: index.md

- 【 Note@-Python 】:
  - Py基础: 
    - 装饰器的使用: pyNotes/python基础/decator.md
  - Py常用模块:
    - Select的使用: pyNotes/常用模块/select的使用.md
    - Pickle的使用: pyNotes/常用模块/Pickle的使用.md
  - Py工具集:
    - python操作Excel: pyNotes/Py工具集/python操作excel文件.md
- 【 Note@-Golang 】:
  - Go基础: 
    - goNotes/go-base/No1-环境安装和配置.md
    - goNotes/go-base/No2-go基本知识点.md
    - goNotes/go-base/No3-基本数据类型和数据结构.md
- 【 Note@-Devops 】:
  - kubernetes:
    - 【k8s】集群搭建指南: devopsNotes/kubernetes/kubeadm安装集群指南.md
  # - 【 @study - AI学习 】:
  #   - 编写文档: user-guide/writing-your-docs.md
  # - 【 @study - BigData 】:
  #   - 编写文档: user-guide/writing-your-docs.md
# - 【 @study - 综合 】:
  
# - Life - 时笺:
#   - 予时光以意义: user-guide/writing-your-docs.md
# - About - Self:
#     - 发行说明: about/release-notes.md
    